Project.MVCUI/Controllers/ShoppingController.cs
using PagedList;
using Project.BLL.DesignPatterns.GenericRepository.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using Project.MVCUI.CustomTools;
using Project.MVCUI.VMClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Controllers
{
    public class ShoppingController : Controller
    {
        OrderRepository _oRep;
        ProductRepository _pRep;
        CategoryRepository _cRep;
        OrderDetailRepository _odRep;

        public ShoppingController()
        {
            _pRep = new ProductRepository();
            _odRep = new OrderDetailRepository();
            _oRep = new OrderRepository();
            _cRep = new CategoryRepository();
        }

        /*
         string a = "Mehmet";
         string b = a ?? "Ali";

        Yani burada demek istediğimiz; a null ise b nin değerine Ali yi at demek, ama a null değilse de b nin değerine a yı(Mehmet) at demektir.
         
         */


        
        public ActionResult ShoppingList(int? page, int? categoryID) // nullable i vermemizin sebebi, aslında buradaki int'in kaçıncı sayfada oludğumuzu temsil edecek olmasıdır. Ancak birisi direkt alışveriş sayfasına ulaştığında hangi sayfada oluduğu verisi olamayacağından dolayı bu şekilde de (yani sayfa numarası gönderilmeden de) nu Action'ın çalışabilmesini istiyoruz..
        {
            // page?? => ifadesi page null ise demektir.

            PaginationVM pavm = new PaginationVM()
            {
                PagedProducts = categoryID == null ? _pRep.GetActives().ToPagedList(page ?? 1, 9) : _pRep.Where(x => x.CategoryID == categoryID).ToPagedList(page ?? 1, 9), //page null ise 1. sayfadan başlat, değilse kaçsa oradan başlat. bir sayfada da 9 ürün olsun demek istedik.
                Categories = _cRep.GetActives()
            };

            // Hangi kategoride olduğumu bilgisayarın aklında tutmak için;
            if (categoryID != null) TempData["catID"] = categoryID;  // Herhangi bir kategori seçtik. Bulunacağımız sayfadaki 9 ürün o kategoriden gelecek. Ama başka sayfaya geçtiğimde hangi kategoride bulunduğumu unutacağı için bütün kategorideki ürünleri listelemeye başlayacaktır. O yüzden geçtiğim o sayfaya, seçtiğim kategoride olduğumu bildirmek için TempData kullandık.


            return View(pavm);
        }

        public ActionResult AddToCart(int id) 
        {
            Cart c = Session["scart"] == null ? new Cart() : Session["scart"] as Cart;  // Sepeti yakalamamız lazım. Eğer Session boşsa yeni bir Cart yaratacak, boş değilse mevcut Session'ı kullanacak. (Session object tipte değer tutar.)
            Product eklenecekUrun = _pRep.Find(id);  // Hangi ürünün ekleneceğini buluyoruz..

            CartItem ci = new CartItem   // Yakaladığımız eklenecek ürünün bilgilerini alacak..
            {
                ID = eklenecekUrun.ID,
                Name = eklenecekUrun.ProductName,
                Price = eklenecekUrun.UnitPrice,
                ImagePath = eklenecekUrun.ImagePath
            };

            c.SepeteEkle(ci);
            Session["scart"] = c;
            return RedirectToAction("ShoppingList");
        }

        public ActionResult CartPage()
        {
            if(Session["scart"] != null)
            {
                CartPageVM cpvm = new CartPageVM();
                Cart c = Session["scart"] as Cart;
                cpvm.Cart = c;
                return View(cpvm);
            }

            TempData["bos"] = "Sepetinizde ürün bulunmamaktadır.";
            return RedirectToAction("ShoppingList");
        }

        public ActionResult DeleteFromCart(int id)
        {
            if(Session["scart"] != null)
            {
                Cart c = Session["scart"] as Cart;
                c.SepettenSil(id);
                if(c.Sepetim.Count == 0)
                {
                    Session.Remove("scart");
                    TempData["sepetBos"] = "Sepetinizde ürün bulunmamaktadır.";
                    return RedirectToAction("ShoppingList");
                }
                return RedirectToAction("CartPage");
            }
            return RedirectToAction("ShoppingList");
        }

        public ActionResult SiparisiOnayla()
        {
            AppUser mevcutKullanici;
            if (Session["member"] != null)
            {
                mevcutKullanici = Session["member"] as AppUser;
            }
            else TempData["anonim"] = "Kullanıcı üye değil";
            return View();
        }

        // https://localhost:44312/api/Payment/ReceivePayment
        // WebApiRestService.WebApiClient kütüphanesini indirmeyi unutmayın çünkü API ile bu kütüphane sayesinde BackEnd'in haberleşmesini sağlayacağız...

        [HttpPost]
        public ActionResult SiparisiOnayla(OrderVM ovm)
        {
            bool result;
            Cart sepet = Session["scart"] as Cart;

            if (Session["member"] != null)
            {
                AppUser kullanici = Session["member"] as AppUser;
                ovm.Order.Email = kullanici.Email;
                ovm.Order.UserName = kullanici.UserName;
                ovm.Order.AppUserID = kullanici.ID;
            }
            else ovm.Order.UserName = TempData["anonim"].ToString();

            ovm.Order.TotalPrice = ovm.PaymentDTO.ShoppingPrice = sepet.TotalPrice;


            #region APISection  
            // API ile haberleşiyoruz.. (BackEnd'den API'a istek yaparız(client), API'da bie bir cevap döndürür(Bu cevaplar BackEnd'de her zaman Task tipinde tutulurlar.) )

            using(HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44312/api/");  // İstek yapacağımız temel adres

                // BackEnd'den bir istek yaptığımızda her zaman bu API isteklerini Task ile yaparız. Task, bir görev tipi demektir.(Görev yaptıran bir tip)
                Task<HttpResponseMessage> postTask = client.PostAsJsonAsync("Payment/ReceivePayment",ovm.PaymentDTO);

                HttpResponseMessage sonuc;

                try
                {
                    sonuc = postTask.Result;
                }
                catch (Exception)
                {

                    TempData["baglantiRed"] = "Banka bağlantıyı reddetti";
                    return RedirectToAction("ShoppingList");
                }

                if (sonuc.IsSuccessStatusCode) result = true;
                else result = false;
                if(result)
                {
                    _oRep.Add(ovm.Order);  // OrderRepository bu noktada Order'ı eklerken onun ID'sini oluşturuyor.

                    foreach(CartItem item in sepet.Sepetim)
                    {
                        OrderDetail od = new OrderDetail();
                        od.OrderID = ovm.Order.ID;
                        od.ProductID = item.ID;
                        od.TotalPrice = item.SubTotal;
                        od.Quantity = item.Amount;
                        _odRep.Add(od);

                        // Ücret ödendikten sonra Stoktan da düşürelim;
                        Product stokDus = _pRep.Find(item.ID);
                        stokDus.UnitInStock -= item.Amount;
                        _pRep.Update(stokDus);
                    }

                    TempData["odeme"] = "Siparişiniz bize ulaşmıştır..Teşekkür ederiz..";
                    MailService.Send(ovm.Order.Email, body: $"Siparişiniz başarı ile alındı...{ovm.Order.TotalPrice}");
                    Session.Remove("scart"); // Sipariş tamamlandıktan sonra sepeti boşalt..
                    return RedirectToAction("ShoppingList");
                }
                else
                {
                    TempData["sorun"] = "Ödeme ile ilgili bir sorun oluştu. Lütfen bankanız ile iletişime geçiniz..";
                    return RedirectToAction("ShoppingList");
                }

            }

            #endregion


            
        }
    }
}

Project.MVCUI/Views/Shopping/CartPage.cshtml
@model CartPageVM
@{
    ViewBag.Title = "CartPage";
}

<div class="jumbotron">
    Ödemeniz gereken toplam tutar => @Model.Cart.TotalPrice $  .... Siparişi onaylamak için lütfen @Html.ActionLink("tıklayınız","SiparisiOnayla")
</div>

<div class="row product-list">
    @foreach (CartItem item in Model.Cart.Sepetim)
    {
        <div class="col-md-4">
            <section class="panel">
                <div class="pro-img-box">
                    @if(item.ImagePath == null || item.ImagePath == "3" || item.ImagePath.Contains("nightlife"))
                {
                    <img src="~/Pictures/548d1bdd-7d7d-46ad-b318-1bf3133c1cfd.jpg" alt="Resim Yok" width="100" height="300" title="@item.Name"/>
                }
                    else
                {
                        <img src="@item.ImagePath" alt="Resim Yok" width="100" height="300" title="@item.Name" />
                }

                    <a href="@Url.Action("DeleteFromCart", new { id=item.ID})" class="adtocart">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>

                    <div class="panel-body text-center">
                        <h4>
                            <a href="#" class="pro-title" title="@item.Name">
                                @item.Name x @item.Amount
                            </a>
                        </h4>
                        <p class="price">
                            $@item.SubTotal
                        </p>

                    </div>

                </div>
            </section>
        </div>
    }
</div>

Project.MVCUI/Views/Shopping/ShoppingList.cshtml
@model PaginationVM
@{
    ViewBag.Title = "ShoppingList";
}


@TempData["bos"]
@TempData["sepetBos"]
@TempData["baglantiRed"]
@TempData["odeme"]
@TempData["sorun"]

<!-- page start-->
<div class="row">
    <div class="col-md-3">
        <section class="panel">
            <div class="panel-body">
                <input type="text" placeholder="Keyword Search" class="form-control">
            </div>
        </section>
        <section class="panel">
            <header class="panel-heading">
                Category
            </header>
            <div class="panel-body">
                <ul class="nav prod-cat">
                    @foreach (Category item in Model.Categories)
                    {
                        <li style="padding-top:30px">@Html.ActionLink(item.CategoryName, "ShoppingList", new { categoryID = item.ID }, new { @class = "btn btn-primary" })</li>
                    }
                </ul>
            </div>
        </section>

    </div>
    <div class="col-md-9">
        <section class="panel">
            <div class="panel-body">


                <div class="pull-right">
                    <ul class="pagination pagination-sm pro-page-list">
                        @if (TempData["catID"] != null)
                        {
                            <li>@Html.PagedListPager(Model.PagedProducts, page => Url.Action("ShoppingList", new { page, CategoryID = TempData["catID"] }))</li>
                        }
                        else
                        {
                            <li>@Html.PagedListPager(Model.PagedProducts, page => Url.Action("ShoppingList", new { page }))</li>
                        }

                    </ul>
                </div>
            </div>
        </section>

        <div class="row product-list">

            @foreach (Product item in Model.PagedProducts)
            {
                <div class="col-md-4">
                    <section class="panel">
                        <div class="pro-img-box">

                            @if (item.ImagePath == null || item.ImagePath == "3" || item.ImagePath.Contains("nightlife"))
                            {

                                <img src="~/Pictures/548d1bdd-7d7d-46ad-b318-1bf3133c1cfd.jpg" alt="Resim Yok" width="100" height="300" title="@item.ProductName" />

                            }
                            else
                            {
                                <img src="@item.ImagePath" alt="Resim Yok" width="100" height="300" title="@item.ProductName" />
                            }


                            <a href="@Url.Action("AddToCart", new { id=item.ID})" class="adtocart">
                                <i class="icon-shopping-cart"></i>
                            </a>
                        </div>

                        <div class="panel-body text-center">
                            <h4>
                                <a href="#" class="pro-title" title="@item.ProductName">
                                    @item.ProductName | @if (item.Category != null)
                                    {<span>@item.Category.CategoryName</span>}
                                </a>
                            </h4>
                            <p class="price">$@item.UnitPrice</p>
                        </div>
                    </section>
                </div>
            }



        </div>
    </div>
</div>
<!-- page end-->


@section Sepet{
    <li>
        <a href="@Url.Action("CartPage","Shopping")"><i class="icon-shopping-cart"></i></a>

        @if (Session["scart"] != null)
        {
            <span> @((Session["scart"] as Cart).TotalPrice)$ </span>
        }
    </li>

}

@section Member
{
    @if (Session["member"] != null)
    {
        <span class="from">@((Session["member"] as AppUser).UserName)</span>
    }
}

Project.MVCUI/Views/Shopping/SiparisiOnayla.cshtml
@model OrderVM
@{
    ViewBag.Title = "SiparisiOnayla";
}

<div>
    @using (Html.BeginForm())
    {
        <div class="form-group">
            <label class="col-sm-2 control-label">Gönderim Adresi</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.Order.ShippedAddress, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Kart Üzerindeki İsim</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentDTO.CardUserName, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Kart Numarası</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentDTO.CardNumber, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Kart Güvenlik Numarası</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentDTO.SecurityNumber, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Geçerliklik Süresi(Yıl)</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentDTO.CardExpiryYear, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Geçerliklik Süresi(Ay)</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentDTO.CardExpiryMonth, new { @class = "form-control" })
            </div>
        </div>

        if (Session["member"] == null)
        {
            <div class="form-group">
                <label class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    @Html.TextAreaFor(x => x.Order.Email, new { @class = "form-control" })
                </div>
            </div>
        }

        <div class="form-group">
            <label class="col-sm-2 control-label">Onay</label>
            <div class="col-sm-10">
                <button class="btn btn-primary">Onay</button>
            </div>
        </div>
    }
</div>

@section Member
{
    @if (Session["member"] != null)
    {
        <span class="from">@((Session["member"] as AppUser).UserName)</span>
    }
}